fixtures:
  repositories:
    "ssh": "git://github.com/saz/puppet-ssh"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    "chroot_sftp": "#{source_dir}"